namespace CSGSI.Nodes
{
    /// <summary>
    /// Represents a flame that was generated by a molotov/incendiary grenade.
    /// </summary>
    public class Flame
    {
        /// <summary>
        /// The ID of this flame.
        /// </summary>
        public string ID { get; set; }

        /// <summary>
        /// The position of this flame.
        /// </summary>
        public Vector3 Position { get; set; }

        /// <summary>
        /// Initializes a new Flame with the given ID and position.
        /// </summary>
        /// <param name="id">The ID of this flame.</param>
        /// <param name="position">The position of this flame.</param>
        public Flame(string id, Vector3 position)
        {
            ID = id;
            Position = position;
        }
    }
}